services:
  yt-rss:
    build: .
    container_name: yt-rss
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    environment:
      - SLEEP_INTERVAL=360 # 每 6 小时同步一次（分钟）
