import sys
import logging
from pathlib import Path
from typing import Optional, Dict
from datetime import datetime, timezone

import yt_dlp
from main import (
    load_env,
    get_state,
    save_state,
    upload_file,
    download_audio,
    generate_rss,
    fetch_rss_info,
    PREFIX,
    PLAYLIST_URL,
    RSS_FILENAME,
)

# Setup logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

def get_video_info(video_url: str) -> Optional[Dict]:
    """Fetches video metadata using yt-dlp."""
    logger.info(f"Fetching metadata for {video_url}")
    ydl_opts = {
        "quiet": True,
        "no_warnings": True,
    }
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(video_url, download=False)
            
            # Extract upload date
            timestamp = info.get("timestamp")
            upload_date = info.get("upload_date")
            
            if timestamp:
                upload_date = datetime.fromtimestamp(timestamp, tz=timezone.utc).isoformat()
            
            return {
                "id": info["id"],
                "title": info.get("title", ""),
                "description": info.get("description", ""), # Keep description short for RSS
                "upload_date": upload_date,
                "url": video_url
            }
    except Exception as e:
        logger.error(f"Error fetching metadata: {e}")
        return None

def add_video(video_url: str):
    load_env()
    
    # 1. Fetch metadata
    video_info = get_video_info(video_url)
    if not video_info:
        logger.error("Could not fetch video info. Exiting.")
        return

    video_id = video_info["id"]
    prefix = PREFIX or "manual" # Fallback if PREFIX is not set
    
    # 2. Load state
    state = get_state(prefix)
    
    if video_id in state["videos"]:
        logger.info(f"Video {video_id} already exists in state. Regenerating RSS just in case.")
    else:
        # 3. Download audio
        logger.info(f"Downloading audio for {video_id}...")
        download_data = download_audio(video_url, prefix)
        if not download_data:
            logger.error("Download failed.")
            return
        
        # 4. Upload to R2
        logger.info(f"Uploading {download_data['filename']} to R2...")
        upload_file(
            download_data["local_path"],
            f"{prefix}/{download_data['filename']}",
            "audio/mp4",
        )
        
        # Clean up local file
        download_data["local_path"].unlink()
        
        # 5. Update state
        state["videos"][video_id] = {
            "id": video_id,
            "title": video_info["title"],
            "description": video_info["description"],
            "upload_date": video_info["upload_date"],
            "url": download_data["url"],
        }
        save_state(state, prefix)
        logger.info(f"Video {video_id} added to state.")

    # 6. Regenerate RSS
    logger.info("Regenerating RSS feed...")
    # We try to get playlist info for headers, fallback to defaults if PLAYLIST_URL is not suitable
    playlist_info = {
        'title': 'Youtube 同步',
        'name': 'yt-rss',
        'description': 'Generated by yt-rss'
    }
    
    
    generate_rss(state, prefix, playlist_info)
    logger.info("Done!")

def regenerate():
    playlist_info = {
        'title': 'Youtube 同步',
        'name': 'yt-rss',
        'description': 'Generated by yt-rss'
    }
    prefix = PREFIX or "manual" # Fallback if PREFIX is not set
    
    # 2. Load state
    state = get_state(prefix)
    generate_rss(state, prefix, playlist_info)
    logger.info("Done!")

if __name__ == "__main__":
    # regenerate()
    if len(sys.argv) < 2:
        print("Usage: python manual_add.py <youtube_url>")
        sys.exit(1)
    
    url = sys.argv[1]
    add_video(url)
